# Generated by Django 4.2.10 on 2024-02-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='Beginner', max_length=30),
        ),
    ]
